
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Accueil</title>

    <!-- Bootstrap Core CSS -->
    <link href="assets/bootstrap.min.css" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="assets/landing-page.css" rel="stylesheet">

    <!-- Custom Fonts -->
    <link href="assets/font-awesome.min.css" rel="stylesheet" type="text/css">
    <link href="assets/css.css" rel="stylesheet" type="text/css">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body>
    <div class="intro-header">
        <div class="container">

            <div class="row">
                <div class="col-lg-12">
                    <div class="intro-message">
                        <h1>Bienvenue Sur Notre Application</h1>
						<br>
                        <h2>Gestion D'Effectif</h2>
                        <hr class="intro-divider">
                        <ul class="list-inline intro-social-buttons">
                            <li>
                                <a href="Login_Client.Php" class="btn btn-default btn-lg"><span class="network-name"><b>Client</b></span></a>
                            </li>
							
                            <li>
                                <a href="Login_Employe.Php" class="btn btn-default btn-lg"><span class="network-name"><b>Employ&eacute;</b></span></a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>

        </div>
        <!-- /.container -->

    </div>
 
    <!-- Footer -->
    <footer>
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <ul class="list-inline">
                        <li>
                            <a href="Index.Php">Accueil</a>
                        </li>
                        <li class="footer-menu-divider">&sdot;</li>
                        <li>
                            <a href="Propos.Php">A Propos</a>
                        </li>
                        <li class="footer-menu-divider">&sdot;</li>
                        <li>
                            <a href="Contact.Php">Contact</a>
                        </li>
                    </ul>
                    <p class="copyright text-muted small">Gestion D'Effectif &copy; Juin 2015</p>
                </div>
            </div>
        </div>
    </footer>

    <!-- jQuery -->
    <script src="js/jquery.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="js/bootstrap.min.js"></script>

</body>

</html>
